mysql:
  host: 'localhost'
  user: 'root'
  password: ''
  database: 'legado'
recompensas:
  item1:
    title: ''
    sub_title: ''
    comandos:
      - ''
  item2:
    title: ''
    sub_title: ''
    comandos:
      - ''
comandos:
  - 'money set %player% %quantia%'
  - 'cash set %player% %quantia%'
blocos:
  - '1:1'
warp: